### PR TITLE
Add closure for permissions

### PR DESCRIPTION
**Pull request by rvsia**
cc @Hyperkid123 

If this is a correct approach, we can use the same for entitlements and isOrgAdmin.

### CODE REVIEW

**Review by Hyperkid123 — COMMENTED** [review]
Yeah, this is fine. I was quite regularly encountering 500 responses from the user permissions functions. Any change we can add some retries? You know try it 5times before it fails or smth. This is a critical part of the whole landing page.

**Comment by rvsia** [comment]
Ok, I will repeat the load 5x in case it fails.

**Comment by rvsia** [comment]
@Hyperkid123 I updated the code - the function repeats itself 5x in case of any issues. In case it won't work at all, the permissions are empty, so tiles will be just hidden, but we should prepare some `something went wrong` screen, but that is a task for a different PR.

**Comment by Hyperkid123** [comment]
@rvsia yeah empty state screen is planned.

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
