### PR TITLE
SPUR fixes #1

### PR DESCRIPTION
**Pull request by epwinchell**
https://docs.google.com/document/d/1MvAAlclOJc_0rLV6ZWbpOHFBfrSBScX8hxx7JBLoDTk/

Relates to: https://github.com/RedHatInsights/frontend-assets/pull/48

- Reduce Carousel arrow size
- Fix Carousel indicator color
- Increase open Accordion header spacing
- Duplicate CTL background images; hide in mobile

Screen Shot 2021-08-16 at 3 28 42 PM

### CODE REVIEW

**Comment by epwinchell** [comment]
cc @beccaglass

**Comment by beccaglass** [comment]
@epwinchell awesome!! Can we make the carousel arrow the same color as the indicator on the bottom?

**Comment by epwinchell** [comment]
>  Can we make the carousel arrow the same color as the indicator on the bottom?
@beccaglass Good catch - I forgot the variable's case sensitive
Screen Shot 2021-08-16 at 4 01 11 PM

**Comment by beccaglass** [comment]
@epwinchell perfecto!

**Review by karelhala — APPROVED** [review]

**Pull request merged**
