### PR TITLE
add cypress config

### PR DESCRIPTION
**Pull request by InsaneZein**
[RHCLOUD-28829](https://issues.redhat.com/browse/RHCLOUD-28829): Add cypress config to landing page

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@InsaneZein you will have to mock unelash for jest:
```
 Unleash: Fetching feature toggles did not have an ok response
```

**Comment by InsaneZein** [comment]
are there examples of this being done elsewhere?

**Comment by fhlavac** [comment]
Something like
https://github.com/RedHatInsights/insights-chrome/blob/3194deec345de9467832f96eb4ab8326909f0d81/src/components/RootApp/ScalprumRoot.test.js#L30

should be enough

**Pull request merged**
