### PR TITLE
Add option to use useProxy config

### PR DESCRIPTION
**Pull request by rvsia**
cc @karelhala @Hyperkid123

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@rvsia I am getting chunk loading errors for chrome assets. Is there any additional setup required before we can start using the proxy?

**Comment by Hyperkid123** [comment]
@rvsia another observation. After I have switched to node@15 it started working. I was using node@12 before. I have nothing against migrating to the new node, but if the proxy has a node version requirement we have to strictly enforce it by the `engines` property in package.json.

**Comment by rvsia** [comment]
@Hyperkid123 No, there is no additional setup required. Also, I don't see the warning but the functionality is intended. I suggest you have a different node version. I am running `v10.23.3`.

**Comment by Hyperkid123** [comment]
@rvsia well now it does not load at all and the dev server dies after I try to access the site
```

[HPM] Error occurred while trying to proxy request /apps/chrome/js/chrome-root.c1a12eaff7b6d63ced9b.js from ci.foo.redhat.com:1337 to https://ci.cloud.redhat.com/ (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
node:events:304
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:258:15)
    at write_ (node:_http_outgoing:712:11)
    at ServerResponse.end (node:_http_outgoing:812:5)
    at ProxyServer.defaultErrorHandler (/home/martin/insights/landing-page-frontend/node_modules/http-proxy-middleware/lib/handlers.js:76:7)
    at ProxyServer.emit (/home/martin/insights/landing-page-frontend/node_modules/eventemitter3/index.js:210:27)
    at IncomingMessage.proxyError (/home/martin/insights/landing-page-frontend/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:165:18)
    at IncomingMessage.emit (node:events:327:20)
    at abortIncoming (node:_http_server:579:11)
    at socketOnEnd (node:_http_server:596:5)
    at TLSSocket.emit (node:events:339:22)
Emitted 'error' event on ServerResponse instance at:
    at ServerResponse.onerror (node:internal/streams/readable:756:14)
    at ServerResponse.emit (node:events:327:20)
    at emitErrorNt (node:_http_outgoing:690:9)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by rvsia** [comment]
@Hyperkid123  I switched to node 12 and I don't see any errors, it runs well.

**Comment by Hyperkid123** [comment]
@rvsia well we are probably dealing with OS differences at this point.

**Comment by Hyperkid123** [comment]
So, the issues I am having are present only in google chrome. I tried it in FF and it works. I have also tried removing my extensions, running in incognito mode but whenever the debugger is opened, the chunks will eventually stop loading. Usually, I am getting `net::ERR_TOO_MANY_RETRIES` on a random chunk. I will try and turn off source maps, that is the only one thing I can think of which may be causing the network error...

**Comment by Hyperkid123** [comment]
Well after removing the map files, it seems to be stable :crossed_fingers: Occasionally it crashes on chrome chunks. I will try it on prod and see if these crashes occur over there as well (we don't have source maps in prod env).

**Comment by Hyperkid123** [comment]
Ok. After trying it on prod I am almost 100% positive the chunk loading issues are caused by source maps and the chrome browser. Don't know why, but I will try using different source maps generation strategies and see if we can make them work.

**Comment by rvsia** [comment]
@Hyperkid123  Any updates here? 🤔

**Comment by Hyperkid123** [comment]
@rvsia I Totally forgot about this one. I think we can merge it. can you just update to the latest config version?

**Comment by rvsia** [comment]
There is some issue with the custom mutateConfig function when using the latest config.

```jsx
[webpack-cli] Failed to load '/Users/rvsiansk/insights-project/landing-page-frontend/config/dev.webpack.config.js' config
[webpack-cli] TypeError: Cannot read property 'use' of undefined
    at mutateConfig (/Users/rvsiansk/insights-project/landing-page-frontend/config/mutateConfig.js:45:61)
    at Object.<anonymous> (/Users/rvsiansk/insights-project/landing-page-frontend/config/dev.webpack.config.js:29:6)
    at Module._compile (/Users/rvsiansk/insights-project/landing-page-frontend/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/Users/rvsiansk/insights-project/landing-page-frontend/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at loadConfig (/Users/rvsiansk/insights-project/landing-page-frontend/node_modules/webpack-cli/lib/webpack-cli.js:1158:31)
```

**Comment by Hyperkid123** [comment]
@rvsia yeah the loaders have changed. Can you remove/change the CSS-loader entry and see if the images still load properly?

**Comment by rvsia** [comment]
@Hyperkid123 I updated it. I checked the CSS in UI and it seems ok to me, but I am not sure what was wrong. I have also removed some packages, that are managed by the config or are obsolete.

**Comment by Hyperkid123** [comment]
@rvsia can you fixup the linter errors?

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
