### PR TITLE
Fix footer layout

### PR DESCRIPTION
**Pull request by Hyperkid123**
jira: https://issues.redhat.com/browse/RHCLOUD-13165

Icons were not yet provided by apps. Using question mark as a placeholder.

### Large
screenshot-ci foo redhat com_1337-2021 03 25-12_24_04

### Medium
screenshot-ci foo redhat com_1337-2021 03 25-12_25_28

### Small
screenshot-ci foo redhat com_1337-2021 03 25-12_26_10

### CODE REVIEW

**Review by rvsia — APPROVED** [review]
I would maybe change the medium layout to use the whole row, because it does not look good when one item is taking just a half of screen.. but that's a question of taste. 👅

**Comment by epwinchell** [comment]
@rvsia This layout is completely different than what we had before. I'll post screenshots shortly.

**Comment by epwinchell** [comment]
1450px+
107287006-5959da00-6a2f-11eb-8f90-783e7b14e007-2

1200px to 1449px
107287648-3bd94000-6a30-11eb-8640-13a45f764bcb

Up to 1199px
107287011-5bbc3400-6a2f-11eb-8c20-caa4d791f7f6

**Comment by Hyperkid123** [comment]
Ah i see we switch the order. Should be simple enough change.

**Comment by Hyperkid123** [comment]
@epwinchell ok I have the change ready. However, with the dynamic data and different string lengths we have another problem surfacing:


Columns yay! So i will use grid layout instead of flex layout and post an update!

**Comment by Hyperkid123** [comment]
Ok, this is how it looks like now. Seems much better to me. Also, I have switched to exact PF layout breakpoints so we can use the `sm`, `md`, `lg` and `xl` flags.

screenshot-ci foo redhat com_1337-2021 03 25-15_04_04

**Review by rvsia — APPROVED** [review]

**Comment by epwinchell** [comment]
`Ok, this is how it looks like now. Seems much better to me. Also, I have switched to exact PF layout breakpoints so we can use the sm, md, lg and xl flags.`

It looks ook. We were intentionally not using the PF breakpoints, but we can revisit.

**Review by epwinchell — APPROVED** [review]

**Pull request merged**
