### PR TITLE
update subscriptions unentitled modal

### PR DESCRIPTION
**Pull request by cdcabrera**
## What is this
Update the `Subscription Watch` unentitled modal

## Environments
- CI
- QA
- Prod Beta

## Note
- Subs Watch reference https://github.com/RedHatInsights/curiosity-frontend/issues/212
- UI/UX @bclarhk @jeperry @rblackbu

Screen Shot 2020-02-27 at 4 18 33 PM

@ryelo

### CODE REVIEW

**Comment by rblackbu** [comment]
Looks good

**Comment by cdcabrera** [comment]
@jeperry the button here a custom attribute setup... `app-entitlement="subscription-watch"`. The tour is also present on `migration analytics` under the the custom attribute... `app-entitlement="migration-analytics"`

**Comment by jeperry** [comment]
@cdcabrera not sure I follow - but what I'm after is for the tour button here to have the same class as the one on the blocker view in the app, that way with Pendo we can treat these the exact same and call the same exact tour. E.g. my Pendo rule can be 'for any page site wide, if the button has that class, present that tour.' 

BTW When will a person see this dialogue, if we already block within the app?

As for migration analytics - not sure how it is relevant here?

**Comment by ryelo** [comment]
@jeperry This page is drawn up based on the consts.js file to keep things consistent. Currently there isn't an easy way to add a class to a specific element since it's all generated from the `consts.js` file.

The migration-analytics team uses a Pendo tour too and they're targeting the attribute on the button in Pendo to show the tour. I think what @cdcabrera was saying is that you could use that instead of the `.uxui-curiosity__button-tour`.

A user will see this dialogue if their account number doesn't exist. Any user that has a valid account number will be allowed into the subscriptions app and then you can deal with them accordingly.

**Comment by cdcabrera** [comment]
@jeperry 
- Pendo utilizes Sizzle, per their own docs, think jQuery... Sizzle itself should be more than capable of referencing multiple elements using CSS selectors unless Pendo has placed some limitation on custom CSS selectors
- Users who do not have an account number receive this modal. As discussed early this week this replaces the apps internal redirect mechanics 
- Migration Analytics was a reference point for you to view how it was implemented in Pendo using their custom element selector

The remainder of this discussion, unless it concerns copy updates, should probably be handled off to the side so we can keep this PR on track.

**Comment by bclarhk** [comment]
ship it

**Comment by rblackbu** [comment]
Good

**Comment by jeperry** [comment]
ack

**Pull request merged**
